In [1]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [2]:
df.head()

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [10]:
df_1970 = df[(df["year"] == 1970) & (df["entity"].str.contains("^K", regex=True))]
df_1970

          entity      code  year  life_expectancy_0
9591  Kazakhstan       KAZ  1970            60.0490
9668       Kenya       KEN  1970            54.1427
9742    Kiribati       KIR  1970            54.3802
9816      Kosovo  OWID_KOS  1970            54.0023
9891      Kuwait       KWT  1970            67.9771
9965  Kyrgyzstan       KGZ  1970            58.1840

In [11]:
df.set_index("entity")

            code  year  life_expectancy_0
entity
Afghanistan  AFG  1950            28.1563
Afghanistan  AFG  1951            28.5836
Afghanistan  AFG  1952            29.0138
Afghanistan  AFG  1953            29.4521
Afghanistan  AFG  1954            29.6975
...          ...   ...                ...
Zimbabwe     ZWE  2019            61.0603
Zimbabwe     ZWE  2020            61.5300
Zimbabwe     ZWE  2021            60.1347
Zimbabwe     ZWE  2022            62.3601
Zimbabwe     ZWE  2023            62.7748

[21565 rows x 3 columns]

In [12]:
df.set_index(["code","year"])

                entity  life_expectancy_0
code year
AFG  1950  Afghanistan            28.1563
     1951  Afghanistan            28.5836
     1952  Afghanistan            29.0138
     1953  Afghanistan            29.4521
     1954  Afghanistan            29.6975
...                ...                ...
ZWE  2019     Zimbabwe            61.0603
     2020     Zimbabwe            61.5300
     2021     Zimbabwe            60.1347
     2022     Zimbabwe            62.3601
     2023     Zimbabwe            62.7748

[21565 rows x 2 columns]

In [15]:
df.head(3)

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138

In [25]:
df.rename(columns={"entity" : "pais"},inplace=True)

In [26]:
df.loc[df["code"].isnull()]

                                        pais code  year  life_expectancy_0
375                                 Americas  NaN  1770            34.8000
376                                 Americas  NaN  1830            34.8000
377                                 Americas  NaN  1850            35.1000
378                                 Americas  NaN  1870            35.1000
379                                 Americas  NaN  1900            41.0000
...                                      ...  ...   ...                ...
17703  Small Island Developing States (SIDS)  NaN  2019            72.0847
17704  Small Island Developing States (SIDS)  NaN  2020            71.7761
17705  Small Island Developing States (SIDS)  NaN  2021            69.8938
17706  Small Island Developing States (SIDS)  NaN  2022            72.1257
17707  Small Island Developing States (SIDS)  NaN  2023            72.7255

[1348 rows x 4 columns]

In [28]:
df.loc[df["code"].notnull(), ["pais","year","life_expectancy_0"]].head(3)

          pais  year  life_expectancy_0
0  Afghanistan  1950            28.1563
1  Afghanistan  1951            28.5836
2  Afghanistan  1952            29.0138

In [29]:
df.dropna(subset=["code"], inplace=True)
df.isnull().sum()

pais                 0
code                 0
year                 0
life_expectancy_0    0
dtype: int64

In [32]:
resultado = (
    df.groupby("pais")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)
resultado.head(10)

pais
USSR                        32.700000
South Sudan                 37.841631
Sierra Leone                43.189605
Mali                        43.760793
Niger                       44.187513
East Timor                  44.684692
Nigeria                     44.855897
Chad                        45.007786
Central African Republic    45.084431
Malawi                      45.554985
Name: life_expectancy_0, dtype: float64

In [40]:
new_df = df[df["year"].between(1970 , 2023)]

resultado = (
    new_df.groupby("pais")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)
resultado.head(10)

pais
South Sudan                 41.076146
Central African Republic    47.109006
Sierra Leone                47.234867
Chad                        47.391891
Niger                       47.716867
Nigeria                     47.721319
Mali                        48.654591
Somalia                     48.799163
Angola                      49.022959
East Timor                  49.192574
Name: life_expectancy_0, dtype: float64